calender/urls.py
from . import views
from django.urls import path, include

from .views import *

app_name = 'calender'
urlpatterns = [
    # path(r'index/', views.index, name='index'),
    path(r'', views.CalendarView.as_view(), name='calendar'),
    path(r'register/', RegisterUser.as_view(), name='register'),
    path(r'login/', LoginUser.as_view(), name='login'),
    path(r'logout/', logout_user, name='logout'),
    path(r'event/new/', views.event, name='event_new'),
    path(r'event/edit_dsh/(?P<event_id>\d+)/', views.event_dashboards, name='event_edit_to_dashboard'),
    path(r'event/edit_dsh_default/(?P<event_id>\d+)/', views.event_dashboard_default, name='event_edit_to_dashboard_default'),
    path(r'event/edit/(?P<event_id>\d+)/', views.event, name='event_edit'),
    path(r'event/kdelete/(?P<event_id>\d+)/', views.delete_dashboard, name='event_delete_to_dashboard'),
    path(r'event/delete/(?P<event_id>\d+)/', views.delete, name='event_delete'),
    path(r'dashboard', views.dashboard, name='dashboard'),
    path(r'proj_dashboard/(?P<project_id>\d+)/', views.proj_dashboard, name='proj_dashboard'),
    path(r'back', views.back, name='back'),
    path(r'projects', views.get_projects, name='projects'),
    path(r'add/(?P<projects_name>\d+)/', views.add_worker, name='add_worker'),
    path(r'adding', views.add_worker_without_name, name='add_worker_without_name'),
]

djangoProject3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calender.urls'))
]

calender/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    project_name = models.CharField(max_length=150, null=True)
    manager = models.CharField(max_length=150, null=True)
    status = models.CharField(max_length=50, default='To Do')

    @property
    def get_html_url(self):
        url = reverse('calender:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

    @property
    def get_url(self):
        url = reverse('calender:event_edit_to_dashboard', args=(self.id,))
        return url

    @property
    def get_url_default(self):
        url = reverse('calender:event_edit_to_dashboard_default', args=(self.id,))
        return url

    @property
    def get_delete_url(self):
        url = reverse('calender:event_delete', args=(self.id,))
        return url

    @property
    def get_delete_url_dsh(self):
        url = reverse('calender:event_delete_to_dashboard', args=(self.id,))
        return url

    def __str__(self):
        return self.title


class CustomUser(AbstractUser):
    group = models.CharField(max_length=255)


class Projects(models.Model):
    project_name = models.CharField(max_length=150)
    manager = models.CharField(max_length=150)
    worker = models.CharField(max_length=150, null=True)
    def __str__(self):
        return f'{self.project_name}({self.manager})'

    @property
    def get_url(self):
        url = reverse('calender:proj_dashboard', args=(self.id,))
        return url

class Project(models.Model):
    project_name = models.CharField(max_length=150)
    manager = models.CharField(max_length=150)

    def __str__(self):
        return f'{self.project_name}({self.manager})'

    @property
    def get_url(self):
        url = reverse('calender:proj_dashboard', args=(self.id,))
        return url

    @property
    def get_url_add(self):
        url = reverse('calender:add_worker', args=(self.project_name,))
        return url

calender/forms.py
from django.forms import ModelForm, DateInput
from calender.models import Event
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User, Group

from .models import *


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': 'Your username'}))
    email = forms.EmailField(label='Email',
                             widget=forms.EmailInput(attrs={'class': 'form-input', 'placeholder': 'Your email'}))
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Password'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(
        attrs={'class': 'form-input', 'placeholder': 'Repeat password'}))

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'placeholder': 'Your username'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'placeholder': 'Your password'}))

class AddForm(ModelForm):
    class Meta:
        model = Projects
        fields = ('worker', )


class AddForm1(ModelForm):
    project_name = forms.ChoiceField(choices=list(map(lambda a: (a[0], a[0]), Project.objects.all().values_list('project_name'))))
    class Meta:
        model = Projects
        fields = ('project_name', 'worker',)

class EventForm(ModelForm):
    project_name = forms.ChoiceField(choices=list(map(lambda a: (a[0], a[0]), Project.objects.all().values_list('project_name'))))
    status = forms.ChoiceField(choices=[('To Do', 'To Do'),  ('In progress', 'In progress'), ('Review', 'Review'), ('Done', 'Done')])
    class Meta:
        model = Event
        # datetime-local is a HTML5 input type, format to make date time show on fields
        widgets = {
            'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        fields = ('title', 'description', 'start_time', 'end_time', 'project_name', 'status')

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        # input_formats to parse HTML5 datetime-local input to datetime field
        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

class EventForm_NE(ModelForm):
    status = forms.ChoiceField(choices=[('To Do', 'To Do'),  ('In progress', 'In progress'), ('Review', 'Review'), ('Done', 'Done')])
    class Meta:
        model = Event
        # datetime-local is a HTML5 input type, format to make date time show on fields
        widgets = {
            'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        fields = ('title', 'description', 'start_time', 'end_time', 'status')

    def __init__(self, *args, **kwargs):
        super(EventForm_NE, self).__init__(*args, **kwargs)
        # input_formats to parse HTML5 datetime-local input to datetime field
        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

calender/views.py
import calendar
from datetime import datetime, date, timedelta
from django.contrib.auth import authenticate, login

import django.db.models
from django.contrib.auth import logout
from django.contrib.auth.models import Group
from django.contrib.auth.views import LoginView
from django.core.checks import messages
from django.db.models import QuerySet
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.utils.safestring import mark_safe
from django.views.generic import CreateView

from .forms import EventForm, RegisterUserForm, LoginUserForm, EventForm_NE, AddForm, AddForm1
from .models import *
from .utils import Calendar


def get_dicts(request):
    projects = Projects.objects.filter(worker=request.user.username)
    todo = Event.objects.filter(manager=request.user.username, status='To Do')
    prog = Event.objects.filter(manager=request.user.username, status='In progress')
    review = Event.objects.filter(manager=request.user.username, status='Review')
    done = Event.objects.filter(manager=request.user.username, status='Done')
    for project in projects:
        if project.project_name == 'personal':
            continue
        todo |= Event.objects.filter(project_name=project.project_name, status='To Do')
        prog |= Event.objects.filter(project_name=project.project_name, status='In progress')
        review |= Event.objects.filter(project_name=project.project_name, status='Review')
        done |= Event.objects.filter(project_name=project.project_name, status='Done')

    return {'todo': todo, 'prog': prog, 'review': review, 'done': done}


class CalendarView(generic.ListView):
    model = Event
    template_name = 'calender/calender.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        # d = get_date(self.request.GET.get('day', None))
        d = get_date(self.request.GET.get('month', None))

        # Instantiate our calendar class with today's year and date
        cal = Calendar(d.year, d.month)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True, username=self.request.user.username)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        my_projects = Project.objects.filter(manager=self.request.user.username)
        my_projects2 = Projects.objects.filter(worker=self.request.user.username)
        res = [proj.project_name for proj in my_projects2]
        my_projects2 = Project.objects.filter(project_name__in=res)
        context['projects'] = [proj for proj in my_projects if proj.project_name != 'personal'] + [proj for proj in
                                                                                                   my_projects2 if
                                                                                                   proj.project_name != 'personal']
        return context


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


def add_worker(request, projects_name):
    instance, form = None, None
    instance = Projects()
    instance.manager = request.user.username
    instance.project_name = projects_name
    form = AddForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('calender:calendar'))

    return render(request, 'calender/add.html', {'form': form})


def add_worker_without_name(request):
    instance, form = None, None

    instance = Projects()
    instance.manager = request.user.username
    form = AddForm1(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.fields['project_name'].choices = list(
            map(lambda a: (a[0], a[0]),
                Project.objects.filter(manager=request.user.username).values_list('project_name')))
        form.save()
        return HttpResponseRedirect(reverse('calender:calendar'))
    form.fields['project_name'].choices = [item
                                           for item in map(lambda a: (a[0], a[0]),
                                                           Project.objects.filter(
                                                               manager=request.user.username).values_list(
                                                               'project_name')) if item[0] != 'personal']

    return render(request, 'calender/add.html', {'form': form})

def event(request, event_id=None):  #
    instance = Event()
    form, status = None, None
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
        if request.user.username == instance.manager:
            form = EventForm(request.POST or None, instance=instance)
            status = 1
        else:
            form = EventForm_NE(request.POST or None, instance=instance)
            status = 0
    else:
        instance = Event()
        instance.manager = request.user.username
        form = EventForm(request.POST or None, instance=instance)
        status = 1

    if request.POST and form.is_valid():
        print(request.user.username)
        if status:
            form.fields['project_name'].choices = list(
                map(lambda a: (a[0], a[0]),
                    Project.objects.filter(manager=request.user.username).values_list('project_name')))
        form.save()
        return HttpResponseRedirect(reverse('calender:calendar'))
    if status:
        form.fields['project_name'].choices = list(
            map(lambda a: (a[0], a[0]),
                Project.objects.filter(manager=request.user.username).values_list('project_name')))

    return render(request, 'calender/event.html',
                  {'form': form, 'flag': False, 'status': bool(event_id), 'instance': instance, 'project': None})


def event_dashboards(request, event_id=None):  # из дашбордов
    instance = Event()
    form = None
    status = None
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
        if request.user.username == instance.manager:
            form = EventForm(request.POST or None, instance=instance)
            status = 1
        else:
            form = EventForm_NE(request.POST or None, instance=instance)
            status = 0
    else:
        instance = Event()
        instance.manager = request.user.username
        form = EventForm(request.POST or None, instance=instance)
        status = 1

    if request.POST and form.is_valid():
        print(request.user.username)
        if status:
            form.fields['project_name'].choices = list(
                map(lambda a: (a[0], a[0]),
                    Project.objects.filter(manager=request.user.username).values_list('project_name')))
        form.save()
        project = get_object_or_404(Project, project_name=instance.project_name, manager=instance.manager)
        return proj_dashboard(request, project.id)
    if status:
        form.fields['project_name'].choices = list(
            map(lambda a: (a[0], a[0]),
                Project.objects.filter(manager=request.user.username).values_list('project_name')))

    project = get_object_or_404(Project, project_name=instance.project_name, manager=instance.manager)
    return render(request, 'calender/event.html',
                  {'form': form, 'flag': True, 'status': bool(event_id), 'instance': instance, 'project': project})


def event_dashboard_default(request, event_id=None):  # з дефолтного
    instance = Event()
    form = None
    status = None
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
        if request.user.username == instance.manager:
            form = EventForm(request.POST or None, instance=instance)
            status = 1
        else:
            form = EventForm_NE(request.POST or None, instance=instance)
            status = 0
    else:
        instance = Event()
        instance.manager = request.user.username
        form = EventForm(request.POST or None, instance=instance)
        status = 1

    if request.POST and form.is_valid():
        if status:
            form.fields['project_name'].choices = list(
                map(lambda a: (a[0], a[0]),
                    Project.objects.filter(manager=request.user.username).values_list('project_name')))
        form.save()
        return HttpResponseRedirect(reverse('calender:dashboard'))
    if status:
        form.fields['project_name'].choices = list(
            map(lambda a: (a[0], a[0]),
                Project.objects.filter(manager=request.user.username).values_list('project_name')))
    return render(request, 'calender/event.html',
                  {'form': form, 'flag': True, 'status': bool(event_id), 'instance': instance, 'project': None})


def delete(request, event_id=None):
    instance = get_object_or_404(Event, pk=event_id)
    instance.delete()
    return HttpResponseRedirect(reverse('calender:calendar'))


def delete_dashboard(request, event_id=None):

calender/templates/calender/add.html
{% extends 'calender/base.html' %}

{% block title %}
    Add
{% endblock %}

{% block content %}
    <div class="clearfix">
        <a class="btn btn-info left" href="{% url 'calender:calendar' %}"> Calendar </a>
    </div>


    <form method="post">
        {% csrf_token %}
        <table class="form form-table">
            {{ form }}
            <tr>
                <td colspan="2">
                    <button type="submit" class="btn btn-info right"> Submit</button>
                </td>
            </tr>
        </table>
    </form>

{% endblock %}

calender/templates/calender/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <link rel="stylesheet" type="text/css" href="{% static 'calender/css/styles.css' %}">
    <title>Django Calendar App</title>
    <style>
        .div_panel_1 a {

        }

        .div_panel_1 a:visited {
            color: black; /* Цвет посещённой ссылки */
        }

        .div_panel_1 a:hover {
            color: white; /* Цвет ссылки при наведении */
            background-color: #9e9e9e;
            border-radius: 12px;
        }
    </style>
</head>
<body>

{% block content %}
{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

{% block script %}
{% endblock %}

</body>
</html>

calender/templates/calender/calender.html
{% extends 'calender/base.html' %}

{% block content %}
    <div class="background-1">
        <div class="head_page">
            <div class="head_toolbar">
                {% if request.user.is_authenticated %}
                    <img src="../../static/calender/images/Desktop-1.png" alt="heyo" width="14%" height="70px"
                         class="logo">
                    <li class="last"> {{ user.username }} | <a href="{% url 'calender:logout' %}">Выйти</a></li>
                {% else %}
                    <img src="../../static/calender/images/Desktop-1.png" alt="heyo" width="245px" height="70px"
                         class="logo">
                    <li class="last"><a href="{% url 'calender:register' %}">Регистрация</a> | <a
                            href="{% url 'calender:login' %}">Войти</a></li>
                {% endif %}
            </div>

            <div class="profi_item">
                {% if request.user.is_authenticated %}
                    <div class="div_panel_1">
                        <div class="div_btn_first">
                            <a class="btn" href="{% url 'calender:event_new' %}"> Create new Event </a>
                        </div>
                        <div class="div_btn">
                            <a class="btn" href="{% url 'calender:dashboard' %}"> Dashboard </a>
                        </div>
                        <div class="div_btn">
                            <a class="btn" href="{% url 'calender:add_worker_without_name' %}"> Add member </a>
                        </div>
                        <div class="line">
                        </div>
                        {% if projects %}
                            <div class="project_head">
                                My projects
                            </div>
                            {% for f in projects %}
                                <div class="project_head color_card">
                                    <div>
                                        {{ f.project_name }}

                                    </div>
                                    <div>
                                        {% if f.manager == request.user.username %}
                                            <a class="btn" href="{{ f.get_url_add }}"> +add </a>
                                        {% else %}
                                        {% endif %}
                                        <a class="btn" href="{{ f.get_url }}"> dashboard </a>
                                    </div>
                                </div>

                            {% endfor %}
                        {% endif %}

                    </div>
                {% else %}
                {% endif %}
                <div class="div_panel_3">

                </div>
                <div class="div_panel_2">
                    {% if request.user.is_authenticated %}

                        <div class="base_panel">
                            <div class="clearfix">
                                <a class="btn btn-info left" href="{% url 'calender:calendar' %}?{{ prev_month }}">
                                    Previous Month </a>
                                <a class="btn btn-info right" href="{% url 'calender:calendar' %}?{{ next_month }}">
                                    Next Month </a>
                            </div>
                            {{ calendar }}
                        </div>
                    {% endif %}
                </div>
            </div>


        </div>
    </div>




{% endblock %}

calender/templates/calender/event.html
{% extends 'calender/base.html' %}

{% block title %}
    Event
{% endblock %}

{% block content %}
    {% if project %}
        <div class="clearfix">
            <a class="btn btn-info left" href="{{ project.get_url }}"> Dashboard </a>
        </div>
    {% else %}
        {% if flag %}
            <div class="clearfix">
                <a class="btn btn-info left" href="{% url 'calender:dashboard' %}"> Dashboard </a>
            </div>
        {% else %}

            <div class="clearfix">
                <a class="btn btn-info left" href="{% url 'calender:calendar' %}"> Calendar </a>
            </div>
        {% endif %}
    {% endif %}


    <form method="post">
        {% csrf_token %}
        <table class="form form-table">
            {{ form }}
            <tr>
                <td colspan="2">
                    <button type="submit" class="btn btn-info right"> Submit</button>
                </td>
            </tr>
        </table>
    </form>
    {% if request.user.username == instance.manager %}
        {% if status %}
                <div class="clearfix">
                    <a class="btn btn-info left" href="{{ instance.get_delete_url }}"> Delete2 </a>
                </div>
            {% else %}
            {% endif %}
    {% else %}
    {% endif %}

{% endblock %}

calender/templates/calender/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link type="text/css" href="{% static 'calender/css/register.css' %}" rel="stylesheet"/>
</head>
<body>
{% block content %}
    <h1>{{ title }}</h1>


    <section class="sign-in">
        <div class="container">
            <div class="signin-content">
                <div class="signin-image">
                    <figure><img src="../../static/calender/images/signin-image.jpg" alt="sing up image"></figure>
                    <a href="{% url 'calender:register' %}" class="signup-image-link">Create an account</a>
                </div>

                <div class="signin-form">
                    <h2 class="form-title">Sign up</h2>
                    <form method="post" class="register-form" id="login-form">
                        {% csrf_token %}

                        {% for f in form %}
                            <div class="form-group">
                                <label for="{{ f.id_for_label }}"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                {{ f }}
                            </div>
                            <div class="form-error">{{ f.errors }}</div>
                        {% endfor %}

                        <div class="form-group form-button">
                            <input type="submit" name="signin" id="signin" class="form-submit" value="Log in"/>
                        </div>
                    </form>
                    <div class="social-login">
                        <span class="social-label">Or login with</span>
                        <ul class="socials">
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>


{% endblock %}
</body>
</html>

calender/templates/calender/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link type="text/css" href="{% static 'calender/css/register.css' %}" rel="stylesheet"/>

</head>
<body>
{% block content %}
<h1>{{title}}</h1>

    <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Sign up</h2>
                        <form method="post" class="register-form" id="register-form">
                        {% csrf_token %}

                        {% for f in form %}
                            <div class="form-group">
                                <label for="{{ f.id_for_label }}"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                {{ f }}
                            </div>
                            <div class="form-error">{{ f.errors }}</div>
                        {% endfor %}

                        <div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                        </div>
                    </form>
                    </div>
                    <div class="signup-image">
                        <figure><img src="../../static/calender/images/signup-image.jpg" alt="sing up image"></figure>
                        <a href="{% url 'calender:login' %}" class="signup-image-link">I am already member</a>
                    </div>
                </div>
            </div>
        </section>

{% endblock %}
</body>
</html>

